from AmazonReviewSpider.html_downloader import Downloader
from AmazonReviewSpider.html_parser import HtmlParser
from AmazonReviewSpider.spider_output import OutPutUse
from AmazonReviewSpider.url_manager import UrlManager